[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22.18.0"
  NPM_VERSION = "10.9.3"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"